devMode: true

app:
  proxyServer:
    address: 0.0.0.0:8080
  
    tls:
      keyPath: /certs/cert.key
      certPath: /certs/hosts

  apiServer:
    address: 0.0.0.0:8000

  logger:
    traceLevel: true
    stdoutOnly: true
  
  mongo:
    uri: mongodb://mongo-container:27017
    username:
    password:
    database: proxy

    collections:
      transactions: transactions
